// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-ksBb8U8mu-X40ajKgFA17q9Knn7cFVU',
    appId: '1:800581983312:web:ae4a817afc41a103490555',
    messagingSenderId: '800581983312',
    projectId: 'guardianly-auth',
    authDomain: 'guardianly-auth.firebaseapp.com',
    storageBucket: 'guardianly-auth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv5Az3GHAi6Ed6NvM5Wa3vKS_8kV3dE8c',
    appId: '1:800581983312:android:c6647cbe4850413e490555',
    messagingSenderId: '800581983312',
    projectId: 'guardianly-auth',
    storageBucket: 'guardianly-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9GRd0zic1T6nCMv6qg04sy7HcpXwLWF8',
    appId: '1:800581983312:ios:3d16531903450f4f490555',
    messagingSenderId: '800581983312',
    projectId: 'guardianly-auth',
    storageBucket: 'guardianly-auth.firebasestorage.app',
    iosBundleId: 'com.example.guardianly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9GRd0zic1T6nCMv6qg04sy7HcpXwLWF8',
    appId: '1:800581983312:ios:3d16531903450f4f490555',
    messagingSenderId: '800581983312',
    projectId: 'guardianly-auth',
    storageBucket: 'guardianly-auth.firebasestorage.app',
    iosBundleId: 'com.example.guardianly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-ksBb8U8mu-X40ajKgFA17q9Knn7cFVU',
    appId: '1:800581983312:web:6ab3cb0a71ab985f490555',
    messagingSenderId: '800581983312',
    projectId: 'guardianly-auth',
    authDomain: 'guardianly-auth.firebaseapp.com',
    storageBucket: 'guardianly-auth.firebasestorage.app',
  );
}
